#!/bin/bash

JIRA_ID=${JIRA_ID:-DL}
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
ALLOWED_BRANCH_REGEX="^(NO-JIRA|(${JIRA_ID}-[0-9]+))-[a-zA-Z0-9_-]+$"

if ! [[ $BRANCH_NAME =~ $ALLOWED_BRANCH_REGEX ]]; then
  echo "Invalid branch name: ${BRANCH_NAME} ❌"
  echo "Allowed pattern '(NO-JIRA|${JIRA_ID}-XYZ)-feature-details'"
  exit 1
fi

echo "Git hooks: Passed branch name validation 🚀"

FLYWAY_VALIDATE_TASK="validateFlywayMigrationScriptsIntegrity"
if ./gradlew tasks --all | grep -qw "${FLYWAY_VALIDATE_TASK}"
then
    ./gradlew $FLYWAY_VALIDATE_TASK
fi
